title: PitchBlack Recovery Project
theme: null

collections:
  oem:
    output: true
    permalink: /devices/:path/

url: "https://PitchBlackRecoveryProject.github.io"
baseurl: ""  # Leave empty for root, or set to "/repo-name" for GitHub Pages under username
permalink: pretty  # Enables clean URLs like /about/ instead of /about.html

# Optional: Add GitHub repo info for Jekyll SEO or metadata plugins
repository: PitchBlackRecoveryProject/PitchBlackRecoveryProject.github.io
